server:
  port: 20012
eureka:
  instance:
    hostname: localhost
#    ip-address: 10.1.3.30
  client:
      service-url:
        defaultZone: http://192.168.2.149:18888/eureka/
      healthcheck:
        enabled: true
    #      defaultZone: http://${eureka.instance.hostname}:28888/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
        #git仓库地址
          uri: https://github.com/luush/open-config-center.git
          #配置路径
          search-paths: testconfig
#          username: your username
#          password: your passord
#仓库分支
      label: master