server:
  port: 20000
eureka:
  instance:
#    hostname: localhost
    ip-address: 10.1.3.30
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://192.168.2.149:18888/eureka/
#      defaultZone: http://${eureka.instance.hostname}:28888/eureka/
spring:
  application:
    name: order-center
#开启熔断
feign:
  hystrix:
    enabled: true