server:
  port: 20006
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:28888/eureka/
spring:
  application:
    name: score-center